[package]
name = "echo-rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1"
actix-files = "0.6"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.16", features = ["derive"] }
